# Generated by Django 5.0 on 2025-12-14 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spesialisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Spesialisasi',
                'verbose_name_plural': 'Spesialisasi',
            },
        ),
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_dokter', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('no_lisensi', models.CharField(max_length=50, unique=True)),
                ('no_str', models.CharField(blank=True, help_text='Surat Tanda Registrasi', max_length=50)),
                ('no_telepon', models.CharField(max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('jam_kerja_mulai', models.TimeField(blank=True, null=True)),
                ('jam_kerja_selesai', models.TimeField(blank=True, null=True)),
                ('hari_kerja', models.CharField(blank=True, help_text='Contoh: Senin-Jumat', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dokter_profile', to=settings.AUTH_USER_MODEL)),
                ('spesialisasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokter.spesialisasi')),
            ],
            options={
                'verbose_name': 'Dokter',
                'verbose_name_plural': 'Dokter',
                'ordering': ['nama'],
            },
        ),
    ]
