# Generated by Django 5.0 on 2025-12-14 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rekam_medis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_hasil', models.DateTimeField(auto_now_add=True)),
                ('dokter_pemeriksa', models.CharField(blank=True, max_length=255)),
                ('hasil_pemeriksaan', models.TextField()),
                ('interpretasi', models.TextField(blank=True)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hasil Lab',
                'verbose_name_plural': 'Hasil Lab',
                'ordering': ['-tanggal_hasil'],
            },
        ),
        migrations.CreateModel(
            name='JenisPemeriksaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('tarif', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('waktu_hasil', models.IntegerField(default=1, help_text='Dalam hari')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jenis Pemeriksaan',
                'verbose_name_plural': 'Jenis Pemeriksaan',
            },
        ),
        migrations.CreateModel(
            name='ParameterLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_parameter', models.CharField(max_length=255)),
                ('satuan', models.CharField(blank=True, max_length=50)),
                ('nilai_normal_min', models.FloatField(blank=True, null=True)),
                ('nilai_normal_max', models.FloatField(blank=True, null=True)),
                ('jenis_pemeriksaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='laboratorium.jenispemeriksaan')),
            ],
            options={
                'verbose_name': 'Parameter Lab',
                'verbose_name_plural': 'Parameter Lab',
            },
        ),
        migrations.CreateModel(
            name='DetailHasil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('normal', models.BooleanField(default=True)),
                ('hasil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_hasil', to='laboratorium.hasillab')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorium.parameterlab')),
            ],
            options={
                'verbose_name': 'Detail Hasil',
                'verbose_name_plural': 'Detail Hasil',
            },
        ),
        migrations.CreateModel(
            name='PermintaanLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_permintaan', models.CharField(max_length=50, unique=True)),
                ('tanggal_permintaan', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diproses', models.DateTimeField(blank=True, null=True)),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True)),
                ('catatan_dokter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('baru', 'Baru'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='baru', max_length=20)),
                ('total_harga', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_pemeriksaan', models.ManyToManyField(related_name='permintaan', to='laboratorium.jenispemeriksaan')),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permintaan_lab', to='rekam_medis.rekammedis')),
            ],
            options={
                'verbose_name': 'Permintaan Lab',
                'verbose_name_plural': 'Permintaan Lab',
                'ordering': ['-tanggal_permintaan'],
            },
        ),
        migrations.AddField(
            model_name='hasillab',
            name='permintaan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasil', to='laboratorium.permintaanlab'),
        ),
    ]
