# Generated by Django 5.0 on 2025-12-14 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pasien', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tanggal_lahir', models.DateField()),
                ('no_identitas', models.CharField(max_length=20, unique=True)),
                ('alamat', models.TextField()),
                ('kelurahan', models.CharField(blank=True, max_length=100)),
                ('kecamatan', models.CharField(blank=True, max_length=100)),
                ('kabupaten', models.CharField(blank=True, max_length=100)),
                ('provinsi', models.CharField(blank=True, max_length=100)),
                ('kode_pos', models.CharField(blank=True, max_length=10)),
                ('no_telepon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('jenis_asuransi', models.CharField(blank=True, max_length=50)),
                ('no_asuransi', models.CharField(blank=True, max_length=50)),
                ('alergi', models.TextField(blank=True)),
                ('riwayat_penyakit', models.TextField(blank=True)),
                ('golongan_darah', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pasien_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pasien',
                'verbose_name_plural': 'Pasien',
                'ordering': ['-created_at'],
            },
        ),
    ]
