# Generated by Django 5.0 on 2025-12-14 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rekam_medis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriObat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kategori Obat',
                'verbose_name_plural': 'Kategori Obat',
            },
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kode_obat', models.CharField(max_length=50, unique=True)),
                ('kandungan', models.CharField(blank=True, max_length=255)),
                ('dosis', models.CharField(blank=True, max_length=100)),
                ('bentuk', models.CharField(blank=True, help_text='Tablet, Kapsul, Sirup, dll', max_length=100)),
                ('stok', models.IntegerField(default=0)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('efek_samping', models.TextField(blank=True)),
                ('kontraindikasi', models.TextField(blank=True)),
                ('tanggal_kadaluarsa', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apotek.kategoriobat')),
            ],
            options={
                'verbose_name': 'Obat',
                'verbose_name_plural': 'Obat',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_resep', models.CharField(max_length=50, unique=True)),
                ('tanggal_resep', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('baru', 'Baru'), ('diproses', 'Diproses'), ('selesai', 'Selesai'), ('batal', 'Batal')], default='baru', max_length=20)),
                ('total_harga', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resep', to='rekam_medis.rekammedis')),
            ],
            options={
                'verbose_name': 'Resep',
                'verbose_name_plural': 'Resep',
                'ordering': ['-tanggal_resep'],
            },
        ),
        migrations.CreateModel(
            name='DetailResep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('dosis_pemberian', models.CharField(blank=True, max_length=255)),
                ('cara_pemakaian', models.TextField(blank=True)),
                ('lama_penggunaan', models.CharField(blank=True, max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apotek.obat')),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_resep', to='apotek.resep')),
            ],
            options={
                'verbose_name': 'Detail Resep',
                'verbose_name_plural': 'Detail Resep',
            },
        ),
    ]
