# Generated by Django 5.0 on 2025-12-14 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokter', '0001_initial'),
        ('pasien', '0001_initial'),
        ('rekam_medis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tipe', models.CharField(blank=True, help_text='VIP, Kelas 1, Kelas 2, dll', max_length=50)),
                ('jumlah_kasur', models.IntegerField(default=1)),
                ('kasur_tersedia', models.IntegerField(default=1)),
                ('tarif_per_hari', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fasilitas', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ruangan',
                'verbose_name_plural': 'Ruangan',
            },
        ),
        migrations.CreateModel(
            name='RawatInap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rawat_inap', models.CharField(max_length=50, unique=True)),
                ('no_kasur', models.CharField(max_length=20)),
                ('tanggal_masuk', models.DateTimeField(auto_now_add=True)),
                ('tanggal_keluar', models.DateTimeField(blank=True, null=True)),
                ('diagnosa_awal', models.TextField()),
                ('catatan_perawatan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('selesai', 'Selesai'), ('transfer', 'Transfer')], default='aktif', max_length=20)),
                ('total_biaya', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dokter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokter.dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawat_inap', to='pasien.pasien')),
                ('rekam_medis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rekam_medis.rekammedis')),
                ('ruangan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rawat_inap.ruangan')),
            ],
            options={
                'verbose_name': 'Rawat Inap',
                'verbose_name_plural': 'Rawat Inap',
                'ordering': ['-tanggal_masuk'],
            },
        ),
    ]
