# Generated by Django 5.0 on 2025-12-14 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pasien', '0001_initial'),
        ('rawat_inap', '0001_initial'),
        ('rawat_jalan', '0001_initial'),
        ('rekam_medis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanKeuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.IntegerField()),
                ('tahun', models.IntegerField()),
                ('total_pendapatan', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_pembayaran', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_belum_terbayar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laporan Keuangan',
                'verbose_name_plural': 'Laporan Keuangan',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_invoice', models.CharField(max_length=50, unique=True)),
                ('tanggal_invoice', models.DateField(auto_now_add=True)),
                ('tanggal_jatuh_tempo', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diskon', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pajak', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dikirim', 'Dikirim'), ('sebagian', 'Sebagian Bayar'), ('lunas', 'Lunas'), ('batal', 'Batal')], default='draft', max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='pasien.pasien')),
                ('rawat_inap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rawat_inap.rawatinap')),
                ('rawat_jalan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rawat_jalan.rawatjalan')),
                ('rekam_medis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rekam_medis.rekammedis')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoice',
                'ordering': ['-tanggal_invoice'],
            },
        ),
        migrations.CreateModel(
            name='DetailInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_layanan', models.CharField(choices=[('dokter', 'Konsultasi Dokter'), ('obat', 'Obat'), ('lab', 'Laboratorium'), ('tindakan', 'Tindakan'), ('rawat_inap', 'Rawat Inap'), ('lainnya', 'Lainnya')], max_length=20)),
                ('deskripsi', models.CharField(max_length=255)),
                ('jumlah', models.IntegerField(default=1)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_invoice', to='keuangan.invoice')),
            ],
            options={
                'verbose_name': 'Detail Invoice',
                'verbose_name_plural': 'Detail Invoice',
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pembayaran', models.CharField(max_length=50, unique=True)),
                ('tanggal_pembayaran', models.DateTimeField(auto_now_add=True)),
                ('metode', models.CharField(choices=[('tunai', 'Tunai'), ('debit', 'Debit'), ('kredit', 'Kredit'), ('transfer', 'Transfer'), ('cek', 'Cek')], max_length=20)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('keterangan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sukses', 'Sukses'), ('gagal', 'Gagal')], default='pending', max_length=20)),
                ('bukti_pembayaran', models.FileField(blank=True, null=True, upload_to='bukti_pembayaran/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='keuangan.invoice')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
                'ordering': ['-tanggal_pembayaran'],
            },
        ),
    ]
