# Generated by Django 5.0 on 2025-12-14 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokter', '0001_initial'),
        ('pasien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekamMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rekam_medis', models.CharField(max_length=50, unique=True)),
                ('tanggal_pemeriksaan', models.DateTimeField(auto_now_add=True)),
                ('keluhan_utama', models.TextField()),
                ('riwayat_keluhan', models.TextField(blank=True)),
                ('diagnosa', models.TextField()),
                ('tekanan_darah', models.CharField(blank=True, max_length=20)),
                ('denyut_nadi', models.IntegerField(blank=True, null=True)),
                ('suhu_badan', models.FloatField(blank=True, null=True)),
                ('respirasi', models.IntegerField(blank=True, null=True)),
                ('berat_badan', models.FloatField(blank=True, null=True)),
                ('tinggi_badan', models.FloatField(blank=True, null=True)),
                ('pemeriksaan_fisik', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('baru', 'Baru'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='baru', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dokter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokter.dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekam_medis', to='pasien.pasien')),
            ],
            options={
                'verbose_name': 'Rekam Medis',
                'verbose_name_plural': 'Rekam Medis',
                'ordering': ['-tanggal_pemeriksaan'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_icd10', models.CharField(blank=True, max_length=20)),
                ('nama_diagnosis', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='rekam_medis.rekammedis')),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
            },
        ),
        migrations.CreateModel(
            name='TindakanMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tindakan', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
                ('tarif', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tindakan_medis', to='rekam_medis.rekammedis')),
            ],
            options={
                'verbose_name': 'Tindakan Medis',
                'verbose_name_plural': 'Tindakan Medis',
            },
        ),
    ]
