# Generated by Django 5.0 on 2025-12-14 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokter', '0001_initial'),
        ('pasien', '0001_initial'),
        ('rekam_medis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawatJalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kunjungan', models.CharField(max_length=50, unique=True)),
                ('tanggal_kunjungan', models.DateTimeField(auto_now_add=True)),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True)),
                ('keluhan', models.TextField()),
                ('catatan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('terdaftar', 'Terdaftar'), ('menunggu', 'Menunggu'), ('diproses', 'Diproses'), ('selesai', 'Selesai')], default='terdaftar', max_length=20)),
                ('total_biaya', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dokter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokter.dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawat_jalan', to='pasien.pasien')),
                ('rekam_medis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rekam_medis.rekammedis')),
            ],
            options={
                'verbose_name': 'Rawat Jalan',
                'verbose_name_plural': 'Rawat Jalan',
                'ordering': ['-tanggal_kunjungan'],
            },
        ),
        migrations.CreateModel(
            name='Antrian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_antrian', models.DateField(auto_now_add=True)),
                ('nomor_antrian', models.IntegerField()),
                ('waktu_tiba', models.DateTimeField(blank=True, null=True)),
                ('waktu_dipanggil', models.DateTimeField(blank=True, null=True)),
                ('waktu_dilayani', models.DateTimeField(blank=True, null=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('dipanggil', 'Dipanggil'), ('dilayani', 'Dilayani'), ('selesai', 'Selesai')], default='menunggu', max_length=20)),
                ('rawat_jalan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antrian', to='rawat_jalan.rawatjalan')),
            ],
            options={
                'verbose_name': 'Antrian',
                'verbose_name_plural': 'Antrian',
                'ordering': ['tanggal_antrian', 'nomor_antrian'],
            },
        ),
    ]
